runtime: custom
env: flex

entrypoint: php artisan serve --host=0.0.0.0 --port=3306

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  APP_ENV: production
  APP_KEY: YOUR_APP_KEY
  APP_DEBUG: false
  LOG_CHANNEL: stderr
  DB_CONNECTION: mysql
  DB_HOST: 34.55.111.115
  DB_PORT: 3306
  DB_DATABASE: db_notes_cc
  DB_USERNAME: root
  DB_PASSWORD: 
